create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create table if not exists public.workspace_memberships (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null check (email = lower(trim(email))),
  role text not null check (role in ('owner', 'staff', 'client')),
  status text not null default 'pending' check (status in ('pending', 'active', 'suspended', 'revoked')),
  mfa_required boolean not null default true,
  client_id text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, email)
);

create unique index if not exists workspace_memberships_workspace_user_uq
  on public.workspace_memberships (workspace_id, user_id)
  where user_id is not null;

create index if not exists workspace_memberships_workspace_status_idx
  on public.workspace_memberships (workspace_id, status);

create table if not exists public.workspace_membership_events (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  membership_id uuid references public.workspace_memberships(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists workspace_membership_events_workspace_created_idx
  on public.workspace_membership_events (workspace_id, created_at desc);

create table if not exists private.owner_bootstrap_allowlist (
  workspace_id text not null,
  email text not null check (email = lower(trim(email))),
  claimed_by uuid references auth.users(id) on delete set null,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (workspace_id, email)
);

revoke all on table public.workspace_memberships from anon, authenticated;
revoke all on table public.workspace_membership_events from anon, authenticated;
revoke all on table private.owner_bootstrap_allowlist from public, anon, authenticated;
grant select on table public.workspace_memberships to authenticated;
grant select on table public.workspace_membership_events to authenticated;

alter table public.workspace_memberships enable row level security;
alter table public.workspace_membership_events enable row level security;

create or replace function private.is_workspace_owner(
  target_workspace text,
  require_aal2 boolean default true
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select auth.uid()) is not null
    and (not require_aal2 or coalesce((select auth.jwt()->>'aal'), 'aal1') = 'aal2')
    and exists (
      select 1
      from public.workspace_memberships membership
      where membership.workspace_id = target_workspace
        and membership.user_id = (select auth.uid())
        and membership.role = 'owner'
        and membership.status = 'active'
    );
$$;

revoke execute on function private.is_workspace_owner(text, boolean) from public, anon;
grant execute on function private.is_workspace_owner(text, boolean) to authenticated;

drop policy if exists "Members read their own membership" on public.workspace_memberships;
create policy "Members read their own membership"
  on public.workspace_memberships for select
  to authenticated
  using (
    user_id = (select auth.uid())
    or private.is_workspace_owner(workspace_id, true)
  );

drop policy if exists "Owners read membership events" on public.workspace_membership_events;
create policy "Owners read membership events"
  on public.workspace_membership_events for select
  to authenticated
  using (private.is_workspace_owner(workspace_id, true));

create or replace function public.claim_legacy_membership(
  target_workspace text default 'legacy-lines'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := (select auth.uid());
  current_email text;
  confirmed_at timestamptz;
  membership public.workspace_memberships%rowtype;
  bootstrap_allowed boolean := false;
begin
  if current_user_id is null then
    raise exception 'Authentication is required';
  end if;

  select lower(trim(users.email)), users.email_confirmed_at
    into current_email, confirmed_at
  from auth.users
  where users.id = current_user_id;

  if current_email is null or confirmed_at is null then
    raise exception 'A verified email is required';
  end if;

  select * into membership
  from public.workspace_memberships
  where workspace_id = target_workspace
    and user_id = current_user_id
    and status = 'active'
  limit 1;

  if found then
    return to_jsonb(membership);
  end if;

  select * into membership
  from public.workspace_memberships
  where workspace_id = target_workspace
    and email = current_email
    and status = 'pending'
  for update;

  if found then
    update public.workspace_memberships
    set user_id = current_user_id,
        status = 'active',
        updated_at = now()
    where id = membership.id
    returning * into membership;
  else
    select exists (
      select 1
      from private.owner_bootstrap_allowlist bootstrap
      where bootstrap.workspace_id = target_workspace
        and bootstrap.email = current_email
        and bootstrap.claimed_at is null
    ) into bootstrap_allowed;

    if not bootstrap_allowed then
      raise exception 'No active Legacy OS membership is assigned to this verified email';
    end if;

    insert into public.workspace_memberships (
      workspace_id, user_id, email, role, status, mfa_required, created_by
    ) values (
      target_workspace, current_user_id, current_email, 'owner', 'active', true, current_user_id
    )
    on conflict (workspace_id, email) do update
      set user_id = excluded.user_id,
          role = 'owner',
          status = 'active',
          mfa_required = true,
          updated_at = now()
    returning * into membership;

    update private.owner_bootstrap_allowlist
    set claimed_by = current_user_id,
        claimed_at = now()
    where workspace_id = target_workspace
      and email = current_email;
  end if;

  insert into public.workspace_membership_events (
    workspace_id, membership_id, actor_user_id, action, details
  ) values (
    target_workspace,
    membership.id,
    current_user_id,
    'membership.claimed',
    jsonb_build_object('role', membership.role, 'email', membership.email)
  );

  return to_jsonb(membership);
end;
$$;

revoke execute on function public.claim_legacy_membership(text) from public, anon;
grant execute on function public.claim_legacy_membership(text) to authenticated;

create or replace function public.invite_workspace_owner(
  target_workspace text,
  target_email text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(trim(target_email));
  membership public.workspace_memberships%rowtype;
begin
  if not private.is_workspace_owner(target_workspace, true) then
    raise exception 'A two-step verified owner session is required';
  end if;
  if normalized_email = '' or position('@' in normalized_email) < 2 then
    raise exception 'Enter a valid email address';
  end if;

  select * into membership
  from public.workspace_memberships
  where workspace_id = target_workspace and email = normalized_email
  for update;

  if found and membership.status = 'active' then
    return to_jsonb(membership);
  elsif found then
    update public.workspace_memberships
    set role = 'owner',
        status = 'pending',
        mfa_required = true,
        updated_at = now()
    where id = membership.id
    returning * into membership;
  else
    insert into public.workspace_memberships (
      workspace_id, email, role, status, mfa_required, created_by
    ) values (
      target_workspace, normalized_email, 'owner', 'pending', true, (select auth.uid())
    ) returning * into membership;
  end if;

  insert into public.workspace_membership_events (
    workspace_id, membership_id, actor_user_id, action, details
  ) values (
    target_workspace,
    membership.id,
    (select auth.uid()),
    'owner.invited',
    jsonb_build_object('email', membership.email)
  );

  return to_jsonb(membership);
end;
$$;

revoke execute on function public.invite_workspace_owner(text, text) from public, anon;
grant execute on function public.invite_workspace_owner(text, text) to authenticated;

create or replace function public.set_workspace_membership_status(
  target_membership uuid,
  next_status text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  membership public.workspace_memberships%rowtype;
  active_owner_count integer;
begin
  select * into membership
  from public.workspace_memberships
  where id = target_membership
  for update;

  if not found then
    raise exception 'Membership not found';
  end if;
  if not private.is_workspace_owner(membership.workspace_id, true) then
    raise exception 'A two-step verified owner session is required';
  end if;
  if next_status not in ('active', 'suspended', 'revoked') then
    raise exception 'Unsupported membership status';
  end if;
  if next_status = 'active' and membership.user_id is null then
    raise exception 'The invited user must verify their email and claim access first';
  end if;

  if membership.user_id = (select auth.uid()) and next_status <> 'active' then
    select count(*) into active_owner_count
    from public.workspace_memberships
    where workspace_id = membership.workspace_id
      and role = 'owner'
      and status = 'active';
    if active_owner_count <= 1 then
      raise exception 'The final active owner cannot remove their own access';
    end if;
  end if;

  update public.workspace_memberships
  set status = next_status,
      updated_at = now()
  where id = target_membership
  returning * into membership;

  insert into public.workspace_membership_events (
    workspace_id, membership_id, actor_user_id, action, details
  ) values (
    membership.workspace_id,
    membership.id,
    (select auth.uid()),
    'membership.status_changed',
    jsonb_build_object('status', next_status, 'email', membership.email)
  );

  return to_jsonb(membership);
end;
$$;

revoke execute on function public.set_workspace_membership_status(uuid, text) from public, anon;
grant execute on function public.set_workspace_membership_status(uuid, text) to authenticated;

